spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:Ov23liWMWsveZfZV5dxX}
            client-secret: ${GITHUB_CLIENT_SECRET:636d189505d8511d4a8f41d2e3abc5af9272ab2a}
               # we have deleted this client secret
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            scope: repo
            authorization-grant-type: authorization_code
                                  # this is default
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
server:
  port: 8080

github:
  api:
    base-url: https://api.github.com


# git-hub oauth app
# home page: http://localhost:8080
# callback url: http://localhost:8080/login/oauth2/code/github
# ClientId: Ov23liWMWsveZfZV5dxX
# Client Secret: 636d189505d8511d4a8f41d2e3abc5af9272ab2a
